### ISSUE TITLE
How to remove black frames or prevent them

### ISSUE THREAD

**Issue by brunobola** [NickeManarin/ScreenToGif#660]
How to remove black frames or prevent them :(

![HOW_REMOVE_BLACK_FRAMES](https://user-images.githubusercontent.com/10889019/82878350-4a7bd780-9f33-11ea-9ac6-799be5fb7c18.png)

**Comment by yarecky1** [comment]
@brunobola, @NickeManarin I see the same error in version 2.24.2. In 5 secs clip (24 frames/sec) I had one black frame! This is new. I've been using this application for a very long time and never had such a glitch.

**Comment by NickeManarin** [comment]
I can't explain what's happening yet. This isn't new, it happened with a few users a few years ago.

Are you recording with BitBlt or DirectX?

**Comment by brunobola** [comment]
I always use 60FPS.

**Comment by brunobola** [comment]
I see it regardless of "BitBlt" or "DirectX".
But, because I've bee using several screens with 4K can't use Direct-X :(

**Comment by brunobola** [comment]
Perhaps if some function like "remove black/invalid" frames would help a lot.

**Comment by NickeManarin** [comment]
Can you tell me more about your computer?

Which version of ScreenToGif are you using?
Which windows version + build are you running? 
Which graphics card do you have? Are you running the latest driver?

Type Win+R and `winver` to get the version.
![image](https://user-images.githubusercontent.com/14798947/82916380-5756f600-9f48-11ea-8470-8e263266c6ec.png)

**Comment by brunobola** [comment]
Here is the info.

![Screenshot_4](https://user-images.githubusercontent.com/10889019/82917260-1d4b1b80-9f6b-11ea-84cb-199cc1451db8.png)

**Comment by yarecky1** [comment]
Ok, I think I can add two cents to the issue. I tried 4 the same low size clips and all was ok. Then I tried 1 clip with higher resolution (1347 x 688 x 200 frames x 25 fr/sec) and found a black frame in second frame. I use Bitblt.

I switched to DirectX and made 5 high resolution clips (1347 x 688). All was ok.

Then I switched back to BitBlt and again second frame in 217 frames clip was black.

**Comment by yarecky1** [comment]
The same Windows version and compilation. Old built-in graphic card Intel HD Graphics Family. Driver from 10-06-2017, version 20.19.15.4835. I don't think the problem is hidden here.

![View](https://user-images.githubusercontent.com/28206604/82920359-78830b00-9f77-11ea-818d-2b4022d1a0ac.jpg)

**Comment by generic-user** [comment]
I had the same issue, but if I turn off compression, when using memory cache, it stops adding black frames to the stack ...

**Comment by NickeManarin** [comment]
I fixed the issue with BitBlt. I can detect, during recording, when the frame was dropped and ignored it later.
With, or without compression.

I'm going to release a new version, v2.26.1.

Now, what about DirectX? For DirectX, it should already be dropping frames when the capture fails.
Are you people still having issues with it?

**Comment by NickeManarin** [comment]
Try out version 2.26.1

**Comment by yarecky1** [comment]
It seems to work now in all options: BitBlt, DirectX (tested first time now), Memory Cache (also first time now) and Save to file. So far so good :)

**Comment by NickeManarin** [comment]
@yarecky1  Nice :)

@brunobola  Can you check on your end?

**Comment by generic-user** [comment]
@NickeManarin I just tried the update, it did not fix it for me.

## This Setting 
When using these settings it gives me **black frames**.

### Image of settings
![image](https://user-images.githubusercontent.com/1516035/86901394-d70dde00-c10c-11ea-9018-885022608943.png)

**Comment by brunobola** [comment]
I'll test it today and report feedback.

**Comment by NickeManarin** [comment]
@generic-user I tried a few times, without getting black frames.

Version: 2.26.1
BitBlt, MemCache, 200Mb, No compression.
60 fps, fullscreen (1080p).

**Comment by yarecky1** [comment]
@generic-user I also tried your settings few times and didn't get black frames.
Version: 2.26.1
BitBlt, MemCache, 200Mb, No compression.
60 fps, fullscreen (1080p).

**Comment by generic-user** [comment]
Just tested again, and it appears to add black frames whenever there is nothing happening on the screen.
I attached the project here: [black_2.zip](https://github.com/NickeManarin/ScreenToGif/files/4895572/black_2.zip).

Version: 2.26.1
BitBlt, MemCache, 200Mb, No compression.
60 fps, area.

**Comment by brunobola** [comment]
Just test it and confirm that it continues to add black frames.

**Comment by yarecky1** [comment]
@generic-user @brunobola 
I don't confirm it. Used the same settings as above and no black frames.

**Comment by generic-user** [comment]
Just tried again, had to make 15 different recordings before getting black frames. So it's not so easy to reproduce it seems ...
![001](https://user-images.githubusercontent.com/1516035/87138508-d016d500-c29e-11ea-923f-a75cfead1791.gif)

**Comment by brunobola** [comment]
Even in your gif you got black frames.

Please open it in gimp for instance and see for yourself…

 

Melhores Cumprimentos,

Best regards,

 

Bruno Silva Marques

 <tel:%28%2B351%20916%20311%20580> (+351 916 311 580)

 

Antes de imprimir este e-mail, pense bem se é realmente necessário fazê-lo.

Before printing this email, think whether it is really necessary to do so.

 

De: BC <notifications@github.com> 
Enviada: 10 de julho de 2020 10:17
Para: NickeManarin/ScreenToGif <ScreenToGif@noreply.github.com>
Cc: brunobola <brunobola@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [NickeManarin/ScreenToGif] How to remove black frames or prevent them (#660)

 

Just tried again, had to make 15 different recordings before getting black frames. So it's not so easy to reproduce it seems ...
 <https://user-images.githubusercontent.com/1516035/87138508-d016d500-c29e-11ea-923f-a75cfead1791.gif>

**Comment by generic-user** [comment]
> Even in your gif you got black frames.

Indeed, that's exactly my point. Sorry if it was not clear. English is not my mother language.

**Comment by NickeManarin** [comment]
An option was added to prevent the insertion of black frames when capturing with BitBlt + frame cache.
It's optional because it adds a little overhead in the capture process.
